#!/bin/bash

count=0;

print_files(){
  for file in $1/*
  do
    if [ -d "$file" ]
    then
      #echo "katalog: $file"
      print_files "$file"
    else
      #echo "plik: $file"
      count=$(( $count + 1 ))
      ./codegen.Darwin "$file" 10 30 > H
      curl -F "api_key=DMEE6FFUDMWAMAVZH" -F "query=@H" "http://developer.echonest.com/api/v4/song/identify" > result
      cat result
    fi
  done
}
